services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: urlshortener
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  backend:
    build: ./backend
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASS=postgres
      - DB_NAME=urlshortener
    volumes:
      - ./backend:/app
    command: npm run start:dev

  frontend:
    image: node:20-alpine
    working_dir: /app
    volumes:
      - ./client:/app
    ports:
      - "3001:3001"
    command: sh -c "npm install && npm run dev -- --host --port 3001"

volumes:
  db_data:
